server:
  port: 8090
jwt:
  secret: aVeryLongAndSecureSecretKeyThatHas32CharsOrMore!
spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trading_platform
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
      
internal:
  jwt:
    secret: my-internal-secret-key-should-be-very-secure
    expiration-millis: 60000


  redis:
    host: localhost
    port: 6379
    # password: your_password  # if Redis has auth
