server:
  port: 0
spring:
  application:
    name: shared-dto
internal:
  jwt:
    secret: my-internal-secret-key-should-be-very-secure
    expiration-millis: 60000

  redis:
    host: localhost
    port: 6379

